version: '3.8'

services:
  pikleech:
    image: ghcr.io/akasls/pikleech:latest
    container_name: pikleech
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data

